### ISSUE TITLE
Question: which labels are used for zero-anaphora resolution? 

### ISSUE THREAD

**Issue by TalitaGroetzinger** [YiweiJiang2015/RISeC#2]
Hi,  

I was wondering whether the annotations that carry zero-anaphora (ZAV) 
are also available in the dataset published here. I looked for the tag "ZAV" but could not find it. 
Or am I missing something here?

**Comment by YiweiJiang2015** [comment]
Hi,

The ZAV labels are inferred from the current annotations. Below, I pasted excerpts from `000_English_Walnut_Pie.ann` and its corresponding recipe text:
```
# anno file
id     entity_type   char_start   char_end    mention
=============================
T1	AC 3 10	Preheat
T2	TOOL 11 15	oven
T3	TEMPERATURE 19 32	400 degrees F
T4	TEMPERATURE 34 47	205 degrees C
T5	AC 53 57	BeatT6	FOOD 58 66	the eggs
T7	TOOL 70 82	a large bowl
T8	AC 87 93	Mix in
==============================
id     relation_type   src             tgt
==============================
R23	Arg2_PPT_Z   Arg1:T8     Arg2:T5	
R24	Arg2_PPT_Z   Arg1:T19   Arg2:T16	
R25	Arg1_PPT_X   Arg1:T24   Arg2:T21
```
```
# recipe text
1) Preheat oven to 400 degrees F (205 degrees C).
2) Beat the eggs in a large bowl.
3) *Mix in* sugar, salt, vanilla, and syrup.
```
Those entities which appear in `src` field of a relation type affixed by `_Z` or `_X` are zero anaphora verbs. In this sense, T8 `mix in` is ZAV within the `R23` relation. If you look at the step 3) of the recipe text, `Mix in` (marked by *) has an implicit argument that is the product of step 2), i.e. egg mixture.

Hope this helps you.

P.S. `_Z` or `_X` do not have any semantic meanings. They exist here for easier annotation work.

**Comment by TalitaGroetzinger** [comment]
Thank you!!
